### ISSUE TITLE
Switch state unknown

### ISSUE THREAD

**Issue by DJBenson** [sirkirby/unifi-network-rules#59]
The switches created by this integration appear to be of the type "opportunistic" (i.e. the switch does not know the state of the downstream entity) which results in the switches showing as two toggle entities rather than an actual stateful switch (apologies if I've described this incorrectly but this is how I've seen stateless switches/those in opportunistic mode) operate.

Here's what they look like in the UI;

![Image](https://github.com/user-attachments/assets/10417d5f-8c6e-4e93-91b1-1ea9d309ab20)

Toggling the switch in some of my other integrations forces it to realise it's a stateful switch and the lightning bolts get replaced with an toggle entity. 

Am I misunderstanding fundamentally how this is working or can these be made "proper" switches?

**Installation method**: Home Assistant OS
**Core**: 2025.5.3
**Supervisor**: 2025.05.3
**Operating System**: 15.2
**Frontend**: 20250516.0

**Integration**: 2.2.0

**Comment by DJBenson** [comment]
I can create a template switch but it has strange behaviour. 

![Image](https://github.com/user-attachments/assets/1b9f8d8f-8253-45d5-805f-8635303653de)

Toggling the switch controls the rule on the UDM-SE.

![Image](https://github.com/user-attachments/assets/0fbfd1d0-2b25-4fea-ad11-e280c75c0701)

However the native switches don't update.

![Image](https://github.com/user-attachments/assets/2e5523f3-601c-46dd-bcf0-ced03ee79fc5)

![Image](https://github.com/user-attachments/assets/a05fa480-0f14-48bf-a832-4a8410ce827d)

**Comment by sirkirby** [comment]
hmm. that is odd behavior. yes, you are correct that all switches are designed to be opportunistic and eventually consistent. to ensure that happens, each toggle is queued and then eventually processes with appropriate wait times and backoffs to avoid any rate limiting. So a lot of effort went into ensuring that what you are describing doesn't happen. I would love to figure out why and resolve it. would you mind turning on debug logging, then reproduce this, then turn off logging and post that here. It will be a lot of information, but that should give some insight into what is going on. I'm guessing its an issue with the queue, but hard to know for certain.

**Comment by DJBenson** [comment]
Thanks for the response.

Can we just take the first part of my report as I'm not sure if I've overcomplicated the situation (and I've certainly confused myself now 😄).

The first screenshot - is that how your switches render in HA or do you see switches/toggles?

**Comment by sirkirby** [comment]
ahh, yeah that is just the default view, you can use the switches with any type of button, like a standard up/down toggle. just add a standard button template to your dashboard and assign your entity. This is one of mine that is tied to a firewall policy:

![Image](https://github.com/user-attachments/assets/592abd92-e79f-4944-973e-3f94a23f094d)

**Comment by DJBenson** [comment]
The only time I've really seen a switch represented as the two icons is with Zigbee2MQTT when it's restarting (or HA is starting). The entities initially appear as the two lightning bolts but then they update to a standard toggle switch within a few seconds. It's not a bigge if that's the way it's supposed to work, just thought it unusual.

Thanks for the dialog - it's great when a developer is responsive to feedback like this!

**Comment by sirkirby** [comment]
I just added a new [beta release](https://github.com/sirkirby/unifi-network-rules/releases/tag/v2.2.1-beta.1) for you both to check out, which should solve the issue. I added in some nice default icons as well. you can install the beta via HACS by manually installing the update. Let me know.

**Comment by DJBenson** [comment]
Do I need to do anything special after upgrading because I'm still seeing the old switches. 

- I've downloaded the beta 
- Restarted HA
- Refreshed all data from UniFi
- Cleated the browser cache

**Comment by DJBenson** [comment]
Mmm really not sure what's going on, this is directly from the integration;

![Image](https://github.com/user-attachments/assets/28f2d9a9-a686-41c3-ad67-ff0a7bb071ea)

**Comment by sirkirby** [comment]
That looks right to me. That's how it will always look when browsing the entities on the integration. What you should see in that list are new icons for all of the policies and it will now render as a button when adding to a dashboard.

![image](https://github.com/user-attachments/assets/7d4d14e2-17e8-4342-8396-cf4ad21020f8)

So rather than the lightning bolts, you'll now see this. Basically, I changed all switches to use the outlet switch type by default.

![image](https://github.com/user-attachments/assets/7d3affbc-2b48-447c-b6f8-9867a84e8d35)
